services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ps-tickets-app
    ports:
      - '5432:5432'